; ----------------------------------------------------------------
;  Config by aech
;  Tested on 9800X3D    |  SMT enabled  |  Cores 0-1 isolated
; ----------------------------------------------------------------

[/Script/Engine.Engine]
bUseFixedFrameRate=False
SmoothedFrameRateRange=(LowerBound=(Type=Exclusive,Value=5.000000),UpperBound=(Type=Exclusive,Value=100000.000000))
bSubtitlesEnabled=False

[/Script/Engine.GameEngine]
bIdleWhenNotFocused=False

[/Script/Engine.GarbageCollectionSettings]
gc.TimeBetweenPurgingPendingKillObjects=60
gc.MaxObjectsNotConsideredByGC=500000
gc.NumRetriesBeforeForcingGC=10
gc.AllowParallelGC=1
gc.IncrementalBeginDestroyEnabled=1
gc.CreateGCClusters=1
gc.MinGCClusterSize=10

[/Script/Engine.StreamingSettings]
s.AsyncLoadingThreadEnabled=1
s.WarnIfTimeLimitExceeded=0
s.TimeLimitExceededMultiplier=1.0
s.IoDispatcherBufferSizeKB=1024
s.IoDispatcherBufferCount=32
s.IoDispatcherBufferAlignment=4096
s.IoDispatcherSignatureEnabled=0
s.EventDrivenLoaderEnabled=1

[/Script/Engine.RendererSettings]
r.DefaultFeature.AntiAliasing=0
r.DefaultFeature.Bloom=False

[/Script/Engine.PhysicsSettings]
PhysXTreeRebuildRate=1
bDisableKinematicStaticPairs=True
bDisableKinematicKinematicPairs=True
bSuppressFaceRemapTable=True
bDisableActiveActors=True
bDisableCCD=True
AnimPhysicsMinDeltaTime=0.05

[/Script/SlateCore.SlateSettings]
bExplicitCanvasChildClipping=True
bEnableRetainedRendering=False

[/Script/OnlineSubsystemUtils.IpNetDriver]
NetServerMaxTickRate=120
LanServerMaxTickRate=120

[ConsoleVariables]
r.ShadowQuality=0
r.BloomQuality=0
r.MotionBlurQuality=0
r.AmbientOcclusionLevels=0
r.DepthOfFieldQuality=0
r.LensFlareQuality=0
r.GPUParticle.Enable=0
r.VSync=0
r.SSR=0
r.DistanceFieldAO=0
r.DistanceFieldShadowing=0
r.ContactShadows=0
r.DeferredDecals=0
r.CastShadows=0
r.ReflectionEnvironment=0
r.SkyAtmosphere=0
r.VolumetricCloud=0
r.VolumetricFog=0
Slate.EnableFastWidgetPath=0
Slate.EnableGlobalInvalidation=1

Slate.EnableTooltips=0
Slate.AllowToolTips=0

Slate.CullWidgetsWhenClipping=1
UI.bSuspendRenderingWhenHidden=0
r.Ngx.Enable=0
fx.Niagara.SystemSimulationBatchSize=100
r.GTSyncType=1
t.MaxFrameRateAllowance=0
r.XGEShaderCompile=0

[/Script/Engine.TaskGraphSettings]
bUseThreadPerTaskGraph=True
TaskGraphQueueMode=1

[RenderingThread]
Priority=2

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
AudioCallbackBufferFrameSize=1024
AudioNumBuffersToEnqueue=2
